//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sBackup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sBackup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings are damaged or misconfigured.
        /// </summary>
        internal static string UIMSG_100_APP_MISCONFIG {
            get {
                return ResourceManager.GetString("UIMSG_100_APP_MISCONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///General error has occured:
        ///{0},
        ///in module:
        ///{1}.
        ///
        ///Application stopped
        ///.
        /// </summary>
        internal static string UIMSG_101_GENERAL_ERROR {
            get {
                return ResourceManager.GetString("UIMSG_101_GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing task ID #{0} (type {1}).
        /// </summary>
        internal static string UIMSG_102_TASK_START {
            get {
                return ResourceManager.GetString("UIMSG_102_TASK_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task is disabled. Skipping
        ///.
        /// </summary>
        internal static string UIMSG_103_TASK_DISABLED {
            get {
                return ResourceManager.GetString("UIMSG_103_TASK_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving files from {0}.
        /// </summary>
        internal static string UIMSG_104_ARCHIVING {
            get {
                return ResourceManager.GetString("UIMSG_104_ARCHIVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has finished successfully
        ///.
        /// </summary>
        internal static string UIMSG_105_TASK_DONE_NOERROR {
            get {
                return ResourceManager.GetString("UIMSG_105_TASK_DONE_NOERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing files from {0}.
        /// </summary>
        internal static string UIMSG_106_LISTING_FILES {
            get {
                return ResourceManager.GetString("UIMSG_106_LISTING_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing registry from {0}.
        /// </summary>
        internal static string UIMSG_107_LISTING_REGISTRY {
            get {
                return ResourceManager.GetString("UIMSG_107_LISTING_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup profile file warning:
        ///{0}.
        /// </summary>
        internal static string UIMSG_108_BACKUP_FILE_WARNING {
            get {
                return ResourceManager.GetString("UIMSG_108_BACKUP_FILE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical backup profile file error:
        ///{0}.
        /// </summary>
        internal static string UIMSG_109_BACKUP_FILE_ERROR {
            get {
                return ResourceManager.GetString("UIMSG_109_BACKUP_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file warning:
        ///{0}.
        /// </summary>
        internal static string UIMSG_110_CONFIG_FILE_WARNING {
            get {
                return ResourceManager.GetString("UIMSG_110_CONFIG_FILE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical configuration file error:
        ///{0}.
        /// </summary>
        internal static string UIMSG_111_CONFIG_FILE_ERROR {
            get {
                return ResourceManager.GetString("UIMSG_111_CONFIG_FILE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path doesn&apos;t exist - {0}.
        /// </summary>
        internal static string UIMSG_112_EXCEPTION_FILE_PATH_INVALID {
            get {
                return ResourceManager.GetString("UIMSG_112_EXCEPTION_FILE_PATH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING (skipped) - {0}.
        /// </summary>
        internal static string UIMSG_113_FILE_SKIPPED_EXPORT {
            get {
                return ResourceManager.GetString("UIMSG_113_FILE_SKIPPED_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registry path - {0}.
        /// </summary>
        internal static string UIMSG_114_REG_PATH_INVALID {
            get {
                return ResourceManager.GetString("UIMSG_114_REG_PATH_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registry hive - {0}.
        /// </summary>
        internal static string UIMSG_115_REG_HIVE_INVALID {
            get {
                return ResourceManager.GetString("UIMSG_115_REG_HIVE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRAR has returned an error w/code {0}.
        /// </summary>
        internal static string UIMSG_116_WINRAR_EXCAPTION {
            get {
                return ResourceManager.GetString("UIMSG_116_WINRAR_EXCAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read registry value or open the key {0}, WinRAR is not installed.
        /// </summary>
        internal static string UIMSG_117_WINRAR_NOT_INSTALLED_REGISTRY {
            get {
                return ResourceManager.GetString("UIMSG_117_WINRAR_NOT_INSTALLED_REGISTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid command specified.
        /// </summary>
        internal static string UIMSG_118_CMD_NO_COMMAND {
            get {
                return ResourceManager.GetString("UIMSG_118_CMD_NO_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value was provided for the switch {0}.
        /// </summary>
        internal static string UIMSG_119_CMD_NO_VALUE {
            get {
                return ResourceManager.GetString("UIMSG_119_CMD_NO_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid switch - {0}.
        /// </summary>
        internal static string UIMSG_120_CMD_INVALID_SW {
            get {
                return ResourceManager.GetString("UIMSG_120_CMD_INVALID_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter - {0}.
        /// </summary>
        internal static string UIMSG_121_CMD_INVALID_PARAM {
            get {
                return ResourceManager.GetString("UIMSG_121_CMD_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.{2} .NET
        ///Copyright {3}. All rights reserved
        ///This program is free for personal, educational and/or non-profit usage
        ///.
        /// </summary>
        internal static string UIMSG_123_CMD_LOGO {
            get {
                return ResourceManager.GetString("UIMSG_123_CMD_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versatile command-line backup program, configurable with .xml backup profiles, automating
        ///and simplifying the backup process
        ///
        ///Usage: sBackup &lt;command&gt; /&lt;switch 1&gt; /&lt;switch N&gt; &lt;switch parameter&gt;
        ///
        ///&lt;Commands&gt;
        ///  b             Perform the backup task
        ///
        ///&lt;Switches&gt;
        ///  /NoLogo       Don&apos;t print copyright logo
        ///  /SavePath     Sets the path to save output files. Current directory, if not set
        ///  /ProfileName  Profile name to load. &quot;default&quot; if not set
        ///
        ///Usage examples:
        ///  sBackup b /SavePath E:\
        ///    Read pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UIMSG_124_HELP_TEXT {
            get {
                return ResourceManager.GetString("UIMSG_124_HELP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting backup...
        ///.
        /// </summary>
        internal static string UIMSG_125_START_OM_BACKUP {
            get {
                return ResourceManager.GetString("UIMSG_125_START_OM_BACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All work is done.
        /// </summary>
        internal static string UIMSG_126_WORK_DONE_NOERROR {
            get {
                return ResourceManager.GetString("UIMSG_126_WORK_DONE_NOERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t locate WinRAR in folder {0}, WinRAR is not installed.
        /// </summary>
        internal static string UIMSG_128_WINRAR_NOT_INSTALLED_EXE {
            get {
                return ResourceManager.GetString("UIMSG_128_WINRAR_NOT_INSTALLED_EXE", resourceCulture);
            }
        }
    }
}
